jobs:
    include:
        - os: linux
          name: Ubuntu 18.04
          dist: bionic
        - os: osx
          name: OSX

language: cpp

addons:
    apt:
        packages:
            - xorg-dev

before_install:
    - git submodule init
    - git submodule update
script:
    - cmake .
    - cmake --build .
