jobs:
    include:
        - os: linux
          dist: bionic
        - os: osx

language: cpp

addons:
    apt:
        packages:
            - xorg-dev

before_install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install xcode; fi
    - git submodule init
    - git submodule update
script:
    - cmake .
    - cmake --build .
