name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch submodules
      run: git submodule init
    - name: update submodules
      run: git submodule update
    - name: generate make files
      run: cmake .
    - name: compile
      run: cmake --build .
